### PR TITLE
Looks mergable, yet to test, though.

### PR DESCRIPTION
**Pull request by 0b1kn00b**
I'm poking around the subject of higher types, would this help?

### CODE REVIEW

**Comment by Simn** [comment]
Ah cool, I was going to merge this soon anyway. Thanks!

**Comment by sledorze** [comment]
Thanks @0b1kn00b , @Simn 
When would it be officially released? (we're several in the Starting Blocks...)

**Comment by Simn** [comment]
Don't get your hopes up.

**Comment by 0b1kn00b** [comment]
Happy New Year :/

What's the state of play?

**Pull request merged**
